### ISSUE TITLE
Workers die periodically (because of the request timeout?)

### ISSUE THREAD

**Issue by hatarist** [huge-success/sanic#1079]
This was happening with sanic 0.6.0 + uvloop 0.8.1 and keeps happening with sanic 0.7.0 + uvloop 0.9.1.

I'm not sure I know how to reproduce this. 

    2018-01-03 13:26:19.86 - 30577 - (project.app): exception_handler [INFO]: EXCEPTION_HANDLER: URL='http://***/***', EXCEPTION=ServiceUnavailable('Response Timeout',)
    2018-01-03 13:26:19.92 - 30577 - (project.app): exception_handler [INFO]: Caught an exception
    Traceback (most recent call last):
      File "/home/project/project/env/lib/python3.6/site-packages/sanic/server.py", line 178, in response_timeout_callback
        raise ServiceUnavailable('Response Timeout')
    sanic.exceptions.ServiceUnavailable: Response Timeout
    2018-01-03 13:26:19.93 - 30577 - (asyncio): serve [ERROR]: Exception in callback <bound method HttpProtocol.response_timeout_callback of <sanic.server.HttpProtocol object at 0x7fdf84667710>>
    handle: <TimerHandle HttpProtocol.response_timeout_callback>
    Traceback (most recent call last):
      File "/home/project/project/env/lib/python3.6/site-packages/sanic/server.py", line 178, in response_timeout_callback
        raise ServiceUnavailable('Response Timeout')
    sanic.exceptions.ServiceUnavailable: Response Timeout
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/home/project/project/env/lib/python3.6/site-packages/sanic/server.py", line 416, in write_error
        self.transport.write(response.output(version))
    AttributeError: 'NoneType' object has no attribute 'write'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/home/project/project/env/lib/python3.6/site-packages/sanic/server.py", line 424, in write_error
        repr(e)), from_error=True
      File "/home/project/project/env/lib/python3.6/site-packages/sanic/server.py", line 436, in bail_out
        self.transport.get_extra_info('peername'))
    AttributeError: 'NoneType' object has no attribute 'get_extra_info'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "uvloop/cbhandles.pyx", line 201, in uvloop.loop.TimerHandle._run
      File "/home/project/project/env/lib/python3.6/site-packages/sanic/server.py", line 180, in response_timeout_callback
        self.write_error(exception)
      File "/home/project/project/env/lib/python3.6/site-packages/sanic/server.py", line 430, in write_error
        self.transport.close()
    AttributeError: 'NoneType' object has no attribute 'close'
    2018-01-03 13:26:19.104 - 30577 - (project.app): exception_handler [INFO]: EXCEPTION_HANDLER: URL=None, EXCEPTION=RequestTimeout('Request Timeout',)
    2018-01-03 13:26:19.107 - 30577 - (project.app): exception_handler [INFO]: Caught an exception
    Traceback (most recent call last):
      File "/home/project/project/env/lib/python3.6/site-packages/sanic/server.py", line 162, in request_timeout_callback
        raise RequestTimeout('Request Timeout')
    sanic.exceptions.RequestTimeout: Request Timeout
    python: src/unix/core.c:896: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.

I started the server with the --workers=12, and `ps aux | grep project | wc -l` showed 13 processes (like, the master one and 12 workers); but after such an error it shows one less (12 processes, so one of the workers seems to be dropped dead).

I'll try to fix it myself, just wanted you guys to know about such an issue.

**Comment by r0fls** [comment]
@hatarist this should be fixed on the master branch. I'll leave it open a bit longer in case there is anything else you want to add though.

**Comment by vangheem** [comment]
This issue is still happening to me on master.

**Comment by r0fls** [comment]
@vangheem can you please post the full error log?

**Comment by yunstanford** [comment]
And in Multi-worker mode, Sanic doesn't manage worker processes very well, gunicorn does a better job on that.

**Comment by aljones15** [comment]
not sure if the same issue, but getting this:

 File "/Users/andrewjones/.local/lib/python3.6/site-packages/sanic/server.py", line 162, in request_timeout_callback
    raise RequestTimeout('Request Timeout')

**Comment by ratersnake27** [comment]
Even I am facing this issue when running MonocleMap 
python: src/unix/core.c:896: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
It just stop the scan

**Comment by ywangzi** [comment]
2018-07-02 16:57:00,357 ERROR root:105 | Traceback (most recent call last):
  File "/root/.pyenv/versions/360/lib/python3.6/site-packages/sanic/server.py", line 178, in response_timeout_callback
    raise ServiceUnavailable('Response Timeout')
sanic.exceptions.ServiceUnavailable: Response Timeout

**Comment by ywangzi** [comment]
try:  app.config.RESPONSE_TIMEOUT = 600

**Comment by vvaradarajan** [comment]
I had this error, and debugging showed it was 'my bad' !  The error occurred due to exceptions in async processes that handle websocket input from sanic:
Nov 23 14:28:17 ... start.sh[17457]: Fatal error on transport TCPTransport (error status in uv_stream_t.shutdown callback)
Nov 23 14:28:17 ... start.sh[17457]: protocol: <sanic.websocket.WebSocketProtocol object at 0x7ff978192b48>
Nov 23 14:28:17 ... start.sh[17457]: transport: <TCPTransport closed=False reading=False 0x55d5292329e8>
Nov 23 14:28:17 ... start.sh[17457]: OSError: [Errno 107] Transport endpoint is not connected
The correction was to look at the results of the async process (using asyncio.gather or other asynio methods). The results will show the error. You could also log the async processes with try/except.

**Comment by sohil2609** [comment]
@aljones15 Hi Sir, I am getting same issue when i load test. Did you found any solution from that?

**Comment by aljones15** [comment]
@sohil2609 issue seems to be with the framework thankfully that project changed to java with jersey.

**Comment by ahopkins** [comment]
What is the full exception @sohil2609? How are you deploying Sanic? And, on what architecture?

**Comment by ahopkins** [comment]
Got it. I'll get back to you after the weekend.

**Comment by sohilfynd** [comment]
@ahopkins Getting this exception after some time of load testing "EXCEPTION|WebSocket connection is closed: code = 1005 (no status code [internal]), no reason".

**Comment by sjsadowski** [comment]
The conversation around this issue moved to the forums (https://community.sanicframework.org/t/sanic-server-timeout-isue/153/13) but there has been no real follow-up. Closing, however we can open a new issue if needed.
