### ISSUE TITLE
Multiple requests urls get concatnated resutling a URL not found and subsequent exceptions

### ISSUE THREAD

**Issue by 0x161e-swei** [huge-success/sanic#1211]
This is running on `ubuntu 16.04.4`, kernel `4.13.0-39-generic`, `python 3.5.2`
load generator: https://github.com/sc2682cornell/wrk2 running command
`./wrk -t8 -c32 -d30s -R8000 http://ip:8080/get/256`

The server runs following simple code:
```python
app = Sanic('name')
buf = None
with open('./test_data/256.dat', 'rb') as fin:  
     buf = fin.read()

@app.route('/get/<file_size:int>')   
async def get_file(request, file_size): 
    return response.raw(buf)

app.run('0.0.0.0', port, workers=32)
```

The error message I got:
```python
[2018-04-30 23:02:32 -0500] [18297] [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 546, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/usr/local/lib/python3.5/dist-packages/sanic/router.py", line 344, in get
    return self._get(request.path, request.method, '')
  File "/usr/local/lib/python3.5/dist-packages/sanic/router.py", line 393, in _get
    raise NotFound('Requested URL {} not found'.format(url))
sanic.exceptions.NotFound: Requested URL /get/256/get/256/get/256 not found
[2018-04-30 23:02:32 -0500] [18281] [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/app.py", line 546, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/usr/local/lib/python3.5/dist-packages/sanic/router.py", line 344, in get
    return self._get(request.path, request.method, '')
  File "/usr/local/lib/python3.5/dist-packages/sanic/router.py", line 393, in _get
    raise NotFound('Requested URL {} not found'.format(url))
sanic.exceptions.NotFound: Requested URL /get/256/get/256/get/256/get/256/get/256/get/256 not found
```
I problem I see here is that the requested URL is concatenated with multiple requests while the load generator only sends requests for /get/256

And some subsequent errors like:
```python
AttributeError: 'NoneType' object has no attribute 'should_keep_alive' at server.py:122
local variable 'keep_alive' referenced before assignment at server.py:356
```

**Comment by yunstanford** [comment]
is the load generator reliable https://github.com/sc2682cornell/wrk2 ? can you try wrk or wrk2 ?

**Comment by zezic** [comment]
I can confirm same problem when benchmarking Sanic with wrk2. I'm on Ubuntu 16.04.4 with Python 3.6.3.
`./wrk -t 1 -c 1 -d 1 -R 500 http://localhost:8000/api/item/banana`
```

[2018-05-06 00:41:19 +0300] [2713] [ERROR] Traceback (most recent call last):
  File "/home/shk/Documents/Work/AKB/akbhelp/backend/.venv/lib/python3.6/site-packages/sanic/app.py", line 546, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/shk/Documents/Work/AKB/akbhelp/backend/.venv/lib/python3.6/site-packages/sanic/router.py", line 344, in get
    return self._get(request.path, request.method, '')
  File "/home/shk/Documents/Work/AKB/akbhelp/backend/.venv/lib/python3.6/site-packages/sanic/router.py", line 393, in _get
    raise NotFound('Requested URL {} not found'.format(url))
sanic.exceptions.NotFound: Requested URL /api/item/banana/api/item/banana not found

[2018-05-06 00:41:19 +0300] [2713] [ERROR] Invalid response object for url None, Expected Type: HTTPResponse, Actual Type: <class 'sanic.response.HTTPResponse'>
[2018-05-06 00:41:19 +0300] [2713] [ERROR] Traceback (most recent call last):
  File "/home/shk/Documents/Work/AKB/akbhelp/backend/.venv/lib/python3.6/site-packages/sanic/server.py", line 335, in write_response
    keep_alive = self.keep_alive
  File "/home/shk/Documents/Work/AKB/akbhelp/backend/.venv/lib/python3.6/site-packages/sanic/server.py", line 122, in keep_alive
    self.parser.should_keep_alive())
AttributeError: 'NoneType' object has no attribute 'should_keep_alive'

Task exception was never retrieved
future: <Task finished coro=<Sanic.handle_request() done, defined at /home/shk/Documents/Work/AKB/akbhelp/backend/.venv/lib/python3.6/site-packages/sanic/app.py:519> exception=UnboundLocalError("local variable 'keep_alive' referenced before assignment",)>
Traceback (most recent call last):
  File "/home/shk/Documents/Work/AKB/akbhelp/backend/.venv/lib/python3.6/site-packages/sanic/app.py", line 590, in handle_request
    write_callback(response)
  File "/home/shk/Documents/Work/AKB/akbhelp/backend/.venv/lib/python3.6/site-packages/sanic/server.py", line 356, in write_response
    if not keep_alive:
UnboundLocalError: local variable 'keep_alive' referenced before assignment
[2018-05-06 00:42:19 +0300] [2713] [ERROR] Traceback (most recent call last):
  File "/home/shk/Documents/Work/AKB/akbhelp/backend/.venv/lib/python3.6/site-packages/sanic/server.py", line 178, in response_timeout_callback
    raise ServiceUnavailable('Response Timeout')
sanic.exceptions.ServiceUnavailable: Response Timeout
```

**Comment by 0x161e-swei** [comment]
A little bit digging gives me following:

In some pathological cases, when function `data_received` at [server.py:206](https://github.com/channelcat/sanic/blob/master/sanic/server.py#L206) is called from some uvloop function.
The data object passed into this function actually consists multiple reqeusts: (e.g)
```
b'GET /test/ HTTP/1.1\r\nHost: 10.157.90.165:8080\r\n\r\nGET /test/ HTTP/1.1\r\nHost: 10.157.90.165:8080\r\n\r\n'
```
which results in an invalid URL request of `/test//test/`

**Comment by 1st1** [comment]
I closed the corresponding uvloop issue. The actual problem here is that httptools doesn't support (or does it?) HTTP pipelining.  Unfortunately I don't have time to look at httptools myself at this moment.  Any further investigation/PRs are welcome.

**Comment by yunstanford** [comment]
Yeah, looks like an issue of httptools. But We don't gain a lot from Http 1.1 pipelining though. It'd be better to support http2.

**Comment by ahopkins** [comment]
Closing this since pipelining support will be available once we implement ASGI (coming soon).
