### ISSUE TITLE
websocket example error

### ISSUE THREAD

**Issue by DanielClaudeBaeriswyl** [huge-success/sanic#1277]
sorry very new to this.

**I tried to run the websocket.py example.**
```
import asyncio
from sanic import Sanic
from sanic.response import file

app = Sanic(__name__)

@app.route('/')
async def index(request):
    return await file('websocket.html')

@app.websocket('/feed')
async def feed(request, ws):
    while True:
        data = 'hello!'
        print('Sending: ' + data)
        await ws.send(data)
        data = await ws.recv()
        print('Received: ' + data)

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8002, debug=True)
```

**with the html:**
```
<!DOCTYPE html>
<html>
    <head>
        <title>WebSocket demo</title>
    </head>
    <body>
        <script>
            var ws = new WebSocket('ws://' + document.domain + ':' + location.port + '/feed'),
                messages = document.createElement('ul');
            ws.onmessage = function (event) {
                var messages = document.getElementsByTagName('ul')[0],
                    message = document.createElement('li'),
                    content = document.createTextNode('Received: ' + event.data);
                message.appendChild(content);
                messages.appendChild(message);
            };
            document.body.appendChild(messages);
            window.setInterval(function() {
                data = 'bye!'
                ws.send(data);
                var messages = document.getElementsByTagName('ul')[0],
                    message = document.createElement('li'),
                    content = document.createTextNode('Sent: ' + data);
                message.appendChild(content);
                messages.appendChild(message);
            }, 1000);
        </script>
    </body>
</html>
```

**I get the following error:**
```
[2018-08-03 12:30:24 +0100] [23029] [INFO] Goin' Fast @ http://0.0.0.0:8002
[2018-08-03 12:30:24 +0100] [23029] [INFO] Starting worker [23029]
[2018-08-03 12:30:26 +0100] - (sanic.access)[INFO][1:2]: GET http://0.0.0.0:8002/  200 1140
[2018-08-03 12:30:27 +0100] [23029] [ERROR] Traceback (most recent call last):
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sanic/app.py", line 556, in handle_request
    response = await response
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sanic/app.py", line 259, in websocket_handler
    ws = await protocol.websocket_handshake(request, subprotocols)
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sanic/websocket.py", line 63, in websocket_handshake
    key = handshake.check_request(get_header)
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/websockets/handshake.py", line 83, in check_request
    connection = parse_connection(headers.get('Connection', ''))
AttributeError: 'function' object has no attribute 'get'

[2018-08-03 12:30:27 +0100] [23029] [ERROR] Exception occurred while handling uri: "ws://0.0.0.0:8002/feed"
Traceback (most recent call last):
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sanic/app.py", line 556, in handle_request
    response = await response
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sanic/app.py", line 259, in websocket_handler
    ws = await protocol.websocket_handshake(request, subprotocols)
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/sanic/websocket.py", line 63, in websocket_handshake
    key = handshake.check_request(get_header)
  File "/home/daniel/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/websockets/handshake.py", line 83, in check_request
    connection = parse_connection(headers.get('Connection', ''))
AttributeError: 'function' object has no attribute 'get'

[2018-08-03 12:30:27 +0100] - (sanic.access)[INFO][1:2]: GET ws://0.0.0.0:8002/feed  500 3659
[2018-08-03 12:30:31 +0100] [23029] [INFO] KeepAlive Timeout. Closing connection.
```

Can someone help me with this issue ? Just to get me started. Many thanks !
It is probably fixed easily.

**Comment by Nerevarsoul** [comment]
It's look the same as #1264

**Comment by ahopkins** [comment]
Yeah ... you need to downgrade the `websockets` version that you are using. For example, I have my `requirements.txt` set to: `websockets==5.0.1`.

Or, if you are using pipenv: https://github.com/channelcat/sanic/issues/1264#issuecomment-408100719

**Comment by tadejmagajna** [comment]
I can confirm problem persists with Python 3.7 and 3.6. I temporarily fixed the issue by downgrading websockets to `websockets==6.0`

**Comment by LeehoLim** [comment]
@tadejmagajna what version of Sanic did you use? This still persists when I downgrade to 6.0.

**Comment by ahopkins** [comment]
@LeehoLim Look for this to be upgraded in v19.9 to be released soon.

https://github.com/huge-success/sanic/pull/1635
