### ISSUE TITLE
On Prod, Getting Error: ImportError: cannot import name 'CIDict'

### ISSUE THREAD

**Issue by vikasmcajnu** [huge-success/sanic#1312]
Sanic == 0.8.1
Sanic-Cors == 0.9.3
Connected to pydev debugger (build 181.4668.75)
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/vikas/Documents/fynd/gringotts/app.py", line 7, in <module>
    from sanic_cors import CORS, cross_origin
  File "/Users/vikas/Documents/fynd/venv/gringotts/lib/python3.6/site-packages/sanic_cors/__init__.py", line 11, in <module>
    from .decorator import cross_origin
  File "/Users/vikas/Documents/fynd/venv/gringotts/lib/python3.6/site-packages/sanic_cors/decorator.py", line 16, in <module>
    from .core import *
  File "/Users/vikas/Documents/fynd/venv/gringotts/lib/python3.6/site-packages/sanic_cors/core.py", line 14, in <module>
    from sanic.server import CIDict
ImportError: cannot import name 'CIDict'
Please Fix it on priority.

**Comment by sjsadowski** [comment]
You need to update sanic-cors to 0.9.5 if you're going to use sanic 0.8.1

**Comment by r0fls** [comment]
@vikasmcajnu please try @sjsadowski's solution. Feel free to reopen this issue if you're still having trouble with it

**Comment by vkfynd** [comment]
> @vikasmcajnu please try @sjsadowski's solution. Feel free to reopen this issue if you're still having trouble with it

Thanks for reply. Actually we added sanic check sanic ==0.7.0. It's worked.
