### ISSUE TITLE
Typing error on new install on Union

### ISSUE THREAD

**Issue by Tjorriemorrie** [huge-success/sanic#1321]
Started up a docker image, and ran `pip install sanic` and this is what I get. Not sure how to fix it.
```
>>> from sanic import Sanic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/sanic/__init__.py", line 1, in <module>
    from sanic.app import Sanic
  File "/usr/local/lib/python3.5/site-packages/sanic/app.py", line 17, in <module>
    from sanic.handlers import ErrorHandler
  File "/usr/local/lib/python3.5/site-packages/sanic/handlers.py", line 16, in <module>
    from sanic.response import text, html
  File "/usr/local/lib/python3.5/site-packages/sanic/response.py", line 11, in <module>
    from multidict import CIMultiDict
  File "/usr/local/lib/python3.5/site-packages/multidict/__init__.py", line 18, in <module>
    from ._abc import MultiMapping, MutableMultiMapping
  File "/usr/local/lib/python3.5/site-packages/multidict/_abc.py", line 37, in <module>
    class MutableMultiMapping(MultiMapping[_T], MutableMapping[str, _T]):
  File "/usr/local/lib/python3.5/site-packages/multidict/_abc.py", line 44, in MutableMultiMapping
    def extend(self, *args: _Arg[_T], **kwargs: _T) -> None:
  File "/usr/local/lib/python3.5/typing.py", line 546, in __getitem__
    "Cannot subscript an existing Union. Use Union[u, t] instead.")
TypeError: Cannot subscript an existing Union. Use Union[u, t] instead.
```

**Comment by adamgering** [comment]
We are seeing this too.

**Comment by Tjorriemorrie** [comment]
No need for dockerfile. You can just run:
> docker run --rm python:3.5.2 /bin/bash
then pip install sanic and then try to import it in interpreter.

**Comment by Tjorriemorrie** [comment]
It's working on 3.6, I'll just use that, thanks
