### ISSUE TITLE
multidict-4.1.1 breaks simple example on sanic-0.8.x

### ISSUE THREAD

**Issue by stephanbracke** [huge-success/sanic#1322]
Tested on: Ubuntu 16.04.4 LTS, python 3.5.2
When running the simple example on sanic 0.8.x :
```
from sanic import Sanic
from sanic.response import json
app = Sanic()
@app.route('/')
async def test(request):
    return json({'hello': 'world'})
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
```
I encounter following error

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from sanic import Sanic
  File "/home/stephan/python-virtual-environments/test/lib/python3.5/site-packages/sanic/__init__.py", line 1, in <module>
    from sanic.app import Sanic
  File "/home/stephan/python-virtual-environments/test/lib/python3.5/site-packages/sanic/app.py", line 17, in <module>
    from sanic.handlers import ErrorHandler
  File "/home/stephan/python-virtual-environments/test/lib/python3.5/site-packages/sanic/handlers.py", line 16, in <module>
    from sanic.response import text, html
  File "/home/stephan/python-virtual-environments/test/lib/python3.5/site-packages/sanic/response.py", line 11, in <module>
    from multidict import CIMultiDict
  File "/home/stephan/python-virtual-environments/test/lib/python3.5/site-packages/multidict/__init__.py", line 18, in <module>
    from ._abc import MultiMapping, MutableMultiMapping
  File "/home/stephan/python-virtual-environments/test/lib/python3.5/site-packages/multidict/_abc.py", line 37, in <module>
    class MutableMultiMapping(MultiMapping[_T], MutableMapping[str, _T]):
  File "/home/stephan/python-virtual-environments/test/lib/python3.5/site-packages/multidict/_abc.py", line 44, in MutableMultiMapping
    def extend(self, *args: _Arg[_T], **kwargs: _T) -> None:
  File "/usr/lib/python3.5/typing.py", line 546, in __getitem__
    "Cannot subscript an existing Union. Use Union[u, t] instead.")
TypeError: Cannot subscript an existing Union. Use Union[u, t] instead.
```

pip3 list gives
```
Package       Version
------------- -------
aiofiles      0.4.0  
httptools     0.0.11 
multidict     4.4.1  
pip           18.0   
pkg-resources 0.0.0  
sanic         0.8.3  
setuptools    20.7.0 
ujson         1.35   
uvloop        0.11.2 
websockets    5.0.1  
wheel         0.31.1 

```
Downgrading multidict to 4.4.0 solves the problem, but I'm not sure if it is the right solution

**Comment by yunstanford** [comment]
hey, looks like `multidict` has just published a new version for backward compatibility support.

https://github.com/aio-libs/multidict/releases

you may wanna try that out.

**Comment by stephanbracke** [comment]
Yes, I've just tested it and it solves the issue,
Thanks
