### ISSUE TITLE
problems with jupyter nb

### ISSUE THREAD

**Issue by sshkrv** [huge-success/sanic#1330]
Trying to use simple server example sanic in jupyter notebook, but got an error

`[2018-09-26 13:20:24 +0000] [28544] [INFO] Goin' Fast @ https://127.0.0.1:5005
[2018-09-26 13:20:24 +0000] [28544] [ERROR] Unable to start server
Traceback (most recent call last):
  File "/home/oleg/environments/my_env/lib/python3.6/site-packages/sanic/server.py", line 612, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1442, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1435, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1344, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 451, in uvloop.loop.Loop._run
RuntimeError: Cannot run the event loop while another loop is running
[2018-09-26 13:20:24 +0000] [28544] [INFO] Server Stopped`

**Comment by sjsadowski** [comment]
Can you re-run this with debug mode enabled and share the output? It looks like it's a uvloop issue, which could be handled by disabling uvloop, but it's hard to be sure.

**Comment by sshkrv** [comment]
[2018-09-26 20:05:28 +0000] [4446] [DEBUG] 
[2018-09-26 20:05:28 +0000] [4446] [INFO] Goin' Fast @ https://127.0.0.1:5005
That's all

P.S. When running on python (.py file, same code) it works fine and also writes:
[2018-09-26 20:06:25 +0000] [4560] [INFO] Starting worker [4560]

**Comment by sjsadowski** [comment]
So to clarify: when not running in Jupyter Notebook, your code has no issues, but when running in Jupyter Notebook, it fails?

**Comment by vltr** [comment]
@sshkrv how are you starting the Sanic server?

**Comment by sshkrv** [comment]
@sjsadowski Yes, the problem is only when running on jupyter notebook

@vltr that's my code (from examples):
from sanic import Sanic
from sanic import response

app = Sanic(__name__)

@app.route("/")
async def test(request):
    return response.json({"test": True})
ssl = {'cert' : *my_key*, 'key' : *my_key}
if __name__ == "__main__":
    app.run(port = '5005', ssl=ssl, debug=True)
I have also a redirect in my nginx server from this port, when running .py file it works without mistakes.

**Comment by sjsadowski** [comment]
@sshkrv yes, that would do it. You'll need to hook in to the existing loop.

**Comment by ahopkins** [comment]
@sshkrv There is an example on [how to do that in the docs](https://sanic.readthedocs.io/en/latest/sanic/deploying.html#asynchronous-support).

**Comment by sshkrv** [comment]
@sjsadowski @ahopkins Thank you.

**Comment by c-goosen** [comment]
> I think the problem is maybe because jupyter is using asyncio loop internally, what conflicts with Sanic.

Yeah you are correct, related to this issue: https://github.com/jupyter/notebook/issues/3397
