### ISSUE TITLE
how deploy socket app on heroku

### ISSUE THREAD

**Issue by watchdots** [huge-success/sanic#1367]
Hi everyone!
I write a simple server app with sanic and use sanic.websocket in it.
now, I deploy it on heroku and it return true response when I use from POST, GET methods ,but when I send socket message to it, it will return 500 status.
this is my code:
```
@app.route('/')
async def get(request):
    return text('hi')
@app.websocket('/socket')
async def ws_handler(request, ws):
   data = await ws.recv()
   print(data)
```
and Traceback from heroku logs:
```
2018-10-15T20:01:03.702282+00:00 app[web.1]: [2018-10-15 20:01:03 +0000] [9] [ERROR] Traceback (most recent call last):
2018-10-15T20:01:03.702297+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sanic/app.py", line 603,in handle_request
2018-10-15T20:01:03.702300+00:00 app[web.1]: response = awaitresponse
2018-10-15T20:01:03.702302+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sanic/app.py", line 295,in websocket_handler
2018-10-15T20:01:03.702303+00:00 app[web.1]: ws = await protocol.websocket_handshake(request, subprotocols)
2018-10-15T20:01:03.702304+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sanic/websocket.py", line 69, in websocket_handshake
2018-10-15T20:01:03.702306+00:00 app[web.1]: key = handshake.check_request(get_header)
2018-10-15T20:01:03.702308+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/websockets/handshake.py", line 83, in check_request
2018-10-15T20:01:03.702309+00:00 app[web.1]: connection = parse_connection(headers.get('Connection', ''))
2018-10-15T20:01:03.702311+00:00 app[web.1]: AttributeError: 'function' object has no attribute 'get'
```
and my Procfile:
```
web: python server.py
```
and client code:
```
from websocket import create_connection
ws = create_connection("wss://xorestpythontest.herokuapp.com/api/game")
print("Sending 'Hello, World'...")
ws.send("Hello, World")
```
so, I referred to sanic doc and [deploying](https://sanic.readthedocs.io/en/latest/sanic/deploying.html) part, I see this attribute for app.run()
```sock (default None): Socket for the server to accept connections from.```
but I can't understand what should I do!
so please help me that what should I do for resolve this problem.

**Comment by sjsadowski** [comment]
If the full code above is everything, you're missing critical data. Check out https://sanic.readthedocs.io/en/latest/ for what you're missing

**Comment by ahopkins** [comment]
@watchdots Bring your question over to the community forums and we'll help you out there: http://community.sanicframework.org
