### ISSUE TITLE
When using asyncio.Lock(), RuntimeError occurred: got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by csis0247** [huge-success/sanic#1388]
**Describe the bug**

```
[2018-10-31 16:19:05] [97760] [ERROR] Traceback (most recent call last):
  File "/Users/admin/pyenv/lib/python3.6/site-packages/sanic/app.py", line 603, in handle_request
    response = await response
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "server.py", line 18, in foo2
    async with lock:
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/locks.py", line 181, in acquire
    yield from fut
RuntimeError: Task <Task pending coro=<Sanic.handle_request() running at /Users/admin/pyenv/lib/python3.6/site-packages/sanic/app.py:603> created at /Users/admin/pyenv/lib/python3.6/site-packages/sanic/server.py:295> got Future <Future pending> attached to a different loop

[2018-10-31 16:19:05] [97760] [ERROR] Exception occurred while handling uri: "http://0.0.0.0:1234/2"
Traceback (most recent call last):
  File "/Users/admin/pyenv/lib/python3.6/site-packages/sanic/app.py", line 603, in handle_request
    response = await response
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "server.py", line 18, in foo2
    async with lock:
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/locks.py", line 181, in acquire
    yield from fut
RuntimeError: Task <Task pending coro=<Sanic.handle_request() running at /Users/admin/pyenv/lib/python3.6/site-packages/sanic/app.py:603> created at /Users/admin/pyenv/lib/python3.6/site-packages/sanic/server.py:295> got Future <Future pending> attached to a different loop

[2018-10-31 16:19:05] - (sanic.access)[INFO][127.0.0.1:61823]: GET http://0.0.0.0:1234/2  500 3588
[2018-10-31 16:19:08] - (sanic.access)[INFO][127.0.0.1:61822]: GET http://0.0.0.0:1234/1  200 15
```

**Code snippet**

Below is a self-contained executable code of the server. Run it with `python server.py`. Accessing the routes simultaneously throws the above exception. E.g. try opening 0.0.0.0:1234/1, 0.0.0.0:1234/2, 0.0.0.0:1234/3, 0.0.0.0:1234/4 together.

```
from sanic import Sanic, response
import asyncio

loop = asyncio.get_event_loop()
lock = asyncio.Lock(loop=loop)

if __name__ == '__main__':
    app = Sanic(__name__)

    @app.route('/1')
    async def foo1(request):
        async with lock:
            await asyncio.sleep(3)
            return response.text('Welcome to foo1')

    @app.route('/2')
    async def foo2(request):
        async with lock:
            await asyncio.sleep(3)
            return response.text('Welcome to foo2.')

    @app.route('/3')
    async def foo3(request):
        async with lock:
            await asyncio.sleep(3)
            return response.text('Welcome to foo3.')

    @app.route('/4')
    async def foo4(request):
        async with lock:
            await asyncio.sleep(3)
            return response.text('Welcome to foo4.')
    
    app.go_fast(debug=True, host='0.0.0.0', port=1234, loop=loop, workers=1)
```

**Expected behavior**

I expected the code to successfully lock the route access. Since I passed the same event loop to both Sanic and asyncio.Lock, I did not expect an "attached to a different loop" error, and I am out of my depth trying to debug this. I need to use a lock because parts of some routes have to access a shared resource. Therefore I would like to put a lock on its access. 

**Environment (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Python 3.6.5
 - Sanic 0.8.3

**Additional context**

Below is a toy implementation of asyncio.Lock that one might tryout in Jupyter.

```
import asyncio
import time
loop = asyncio.get_event_loop()
lock = asyncio.Lock(loop=loop)

async def foo(i):
    print('foo()', i, time.time() - start_time)
    async with lock:
        await asyncio.sleep(3)
        print('foo()', i, time.time() - start_time)

async def bar(i):
    print('bar()', i, time.time() - start_time)
    await asyncio.sleep(3)
    print('bar()', i, time.time() - start_time)
```

With Lock:
```
start_time = time.time()
asyncio.run_coroutine_threadsafe(asyncio.wait([foo(i+1) for i in range(4)]), loop)
```
Output:
```
<Future at 0x10896f128 state=pending>
foo() 2 0.00603795051574707
foo() 3 0.006173849105834961
foo() 1 0.006215810775756836
foo() 4 0.006256818771362305
foo() 2 3.008753776550293
foo() 3 6.01404595375061
foo() 1 9.015261888504028
foo() 4 12.016465902328491
```

Without Lock:
```
start_time = time.time()
asyncio.run_coroutine_threadsafe(asyncio.wait([bar(i+1) for i in range(4)]), loop)
```
Output:
```
<Future at 0x10896f160 state=pending>
bar() 2 0.005133867263793945
bar() 1 0.005623817443847656
bar() 4 0.005692005157470703
bar() 3 0.0061037540435791016
bar() 2 3.007520914077759
bar() 1 3.0076818466186523
bar() 4 3.00774884223938
bar() 3 3.0078117847442627
```

**Comment by sjsadowski** [comment]
Not sure what's up here. I was not able to duplicate the errors when testing your code locally, however I have not been able to test on a mac yet.

This is on F28 (kernel 4.18.14-200) w/ python 3.6.6 and sanic 0.8.3

CLI:
```
[user@localhost|git: none| test-sanic]$ curl localhost:1234/1
Welcome to foo1[user@localhost|git: none| test-sanic]$ curl localhost:1234/1
Welcome to foo1[user@localhost|git: none| test-sanic]$ curl localhost:1234/2
Welcome to foo2.[user@localhost|git: none| test-sanic]$ curl localhost:1234/3
Welcome to foo3.[user@localhost|git: none| test-sanic]$ curl localhost:1234/4
```
server logs:
```
[2018-10-31 07:03:43 -0500] [16552] [INFO] Goin' Fast @ http://0.0.0.0:1234
[2018-10-31 07:03:43 -0500] [16561] [INFO] Starting worker [16561]
[2018-10-31 07:03:55 -0500] - (sanic.access)[INFO][127.0.0.1:47266]: GET http://localhost:1234/1  200 15
[2018-10-31 07:04:01 -0500] - (sanic.access)[INFO][127.0.0.1:47270]: GET http://localhost:1234/2  200 16
[2018-10-31 07:04:14 -0500] - (sanic.access)[INFO][127.0.0.1:47278]: GET http://localhost:1234/3  200 16
[2018-10-31 07:04:19 -0500] - (sanic.access)[INFO][127.0.0.1:47282]: GET http://localhost:1234/4  200 16
```

**Comment by sjsadowski** [comment]
I was just able to run this with no issues on OSX Sierra (10.12.6) and python 3.6.4 with no issues, other than async with lock is insanely slow on both platforms.

**Comment by ahopkins** [comment]
@csis0247 The [explanation is in the documentation](https://sanic.readthedocs.io/en/latest/sanic/deploying.html#asynchronous-support) that basically says that if you need to create your own loop, you need to use `app.create_server` instead of `app.run` (`app.go_fast` is an alias of `app.run`).

Change

```
    app.go_fast(debug=True, host='0.0.0.0', port=1234, loop=loop, workers=1)
```

To:

```
    server = app.create_server(host="0.0.0.0", port=1234)
    loop = asyncio.get_event_loop()
    task = asyncio.ensure_future(server)
    loop.run_forever()
```

Then you should be able to operate as expected without errors.

As an FYI, passing `loop=loop` into `app.run` does not do anything. It ignores that loop. It probably should throw an exception to the user so they know not to do it. I am closing this issue for now and will open a separate one. If you have anything further, please feel free to reopen.

**Comment by sjsadowski** [comment]
@ahopkins no need to reopen, but I copied the provided code exactly and ran in to no issues - so if nothing else I'd like to understand the depgraph here so we can isolate the issue. @csis0247 if you're running in a virtualenv can you do a pip freeze > requirements.txt and provide that?

**Comment by yunstanford** [comment]
It's actually not recommended to reference `loop` explicitly, especially in multiprocess mode before `os.fork`. And in most async frameworks, they are close current event loop and spawn a new one for using. and gunicorn also does the same thing
