### ISSUE TITLE
"Task was destroyed but it is pending!" on using response.stream

### ISSUE THREAD

**Issue by syfluqs** [huge-success/sanic#1488]
I am pretty new to async programming and sanic, so bear with me. Following code snippet is from a personal project, it serves a video file in chunks, with support for seeking (taken from #603).

```python
@app.get('/stream')
async def video_stream(request):
    path = get_path_from_request(request)
    _, ext = os.path.splitext(path)
    content_type = f'video/{ext[1:]}'
    headers = {'Content-Type': content_type, 'Accept-Ranges': 'Accept-Ranges: bytes'}
    try:
        with open(path, 'rb') as f:
            range_start = None
            range_end = None
            f.seek(0, 2)
            file_length = f.tell()
            f.seek(0)
            try:
                range_ = f'0-{file_length}'
                if 'range' in request.headers:
                    range_ = request.headers['range'].split('=')[1]
                range_split = range_.split('-')
                range_start = int(range_split[0])
                f.seek(range_start)
                range_end = int(range_split[1])
            except ValueError:
                pass
            if range_start and range_start != 0:
                if not range_end:
                    range_end = file_length
                read_length = range_end - range_start
            else:
                range_start = 0
                read_length = file_length
                range_end = file_length
            f.seek(range_start)
            headers['Content-Length'] = read_length
            headers['Content-Range'] = f'bytes {range_start}-{range_end-1}/{file_length}'
            async def streaming_fn(response):
                with open(path, 'rb') as f:
                    chunk_size = 8192
                    current_offset = range_start
                    while (current_offset < file_length):
                        chunk_start = current_offset
                        f.seek(current_offset)
                        chunk_data = f.read(min(chunk_size, file_length - current_offset))
                        current_offset += chunk_size
                        await response.write(chunk_data)
            return response.stream(streaming_fn, headers=headers, status=206)
    except FileNotFoundError:
        return response.HTTPResponse(status=404)
```

 The video streams fine and seeking is functional. However, the console periodically shows this warning while the video is streaming

```
Exception ignored in: <coroutine object Sanic.handle_request at 0x7f0701810148>
Traceback (most recent call last):
  File "/home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/app.py", line 655, in handle_request
    await stream_callback(response)
  File "/home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py", line 406, in stream_response
    self.keep_alive_timeout_callback)
  File "uvloop/loop.pyx", line 1278, in uvloop.loop.Loop.call_later
  File "uvloop/loop.pyx", line 634, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "app.py", line 7, in <module>
    sanic_app.run_app()
  File "/home/roy/projects/pxx/init/sanic_app.py", line 93, in run_app
    sanic_app.run(host = host, port = port, debug = debug, access_log = access_log, workers = workers)
  File "/home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/app.py", line 730, in run
    serve(**server_settings)
  File "/home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py", line 635, in serve
    loop.run_forever()
  File "/home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py", line 216, in data_received
    self.parser.feed_data(data)
  File "/home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py", line 285, in on_message_complete
    self.execute_request_handler()
  File "/home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py", line 295, in execute_request_handler
    self.stream_response))
task: <Task pending coro=<Sanic.handle_request() running at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/app.py:655> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f0701839dc8>()] created at /usr/lib/python3.7/asyncio/locks.py:290> created at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py:295>
Executing <Task pending coro=<Sanic.handle_request() running at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/app.py:655> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2a33b20d98>()] created at /usr/lib/python3.7/asyncio/locks.py:290> created at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py:295> took 6.124 seconds
Executing <Task pending coro=<Sanic.handle_request() running at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/app.py:655> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2a33943df8>()] created at /usr/lib/python3.7/asyncio/locks.py:290> created at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py:295> took 1.495 seconds
Executing <Task pending coro=<Sanic.handle_request() running at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/app.py:655> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2a33943f18>()] created at /usr/lib/python3.7/asyncio/locks.py:290> created at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py:295> took 1.681 seconds
Executing <Task pending coro=<Sanic.handle_request() running at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/app.py:655> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2a33943f78>()] created at /usr/lib/python3.7/asyncio/locks.py:290> created at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py:295> took 1.274 seconds
Executing <Task pending coro=<Sanic.handle_request() running at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/app.py:655> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f2a317f6198>()] created at /usr/lib/python3.7/asyncio/locks.py:290> created at /home/roy/projects/pxx/venv/lib/python3.7/site-packages/sanic/server.py:295> took 2.187 seconds
```
I think I am using response.stream correctly, as per documentation. Please point out if anything is wrong with the code. 

Also, some additional info, might be useful to debug
- The requests get timed out while the video is still streaming. I have been testing on chrome, and it makes several requests for the stream simultaneously and somehow manages to continue playback without breaks or glitches.
```
[2019-02-09 00:16:23 +0530] [4333] [DEBUG] KeepAlive Timeout. Closing connection.
[2019-02-09 00:16:23 +0530] [4333] [DEBUG] KeepAlive Timeout. Closing connection.
[2019-02-09 00:16:23 +0530] [4333] [DEBUG] KeepAlive Timeout. Closing connection.
[2019-02-09 00:16:23 +0530] [4333] [DEBUG] KeepAlive Timeout. Closing connection.
```
- Following warning lines are also very common
```
Executing <Handle <TaskWakeupMethWrapper object at 0x7f2a317e9618> created at /usr/lib/python3.7/asyncio/locks.py:272> took 0.105 seconds
Executing <Handle <TaskWakeupMethWrapper object at 0x7f2a317e9618> created at /usr/lib/python3.7/asyncio/locks.py:272> took 0.107 seconds
Executing <Handle <TaskWakeupMethWrapper object at 0x7f2a317e9618> created at /usr/lib/python3.7/asyncio/locks.py:272> took 0.132 seconds
Executing <Handle <TaskWakeupMethWrapper object at 0x7f2a317e9618> created at /usr/lib/python3.7/asyncio/locks.py:272> took 0.319 seconds
Executing <Handle <TaskWakeupMethWrapper object at 0x7f2a317e9858> created at /usr/lib/python3.7/asyncio/locks.py:272> took 0.485 seconds
Executing <Handle <TaskWakeupMethWrapper object at 0x7f2a317e9618> created at /usr/lib/python3.7/asyncio/locks.py:272> took 0.180 seconds
Executing <Handle <TaskWakeupMethWrapper object at 0x7f2a317e9618> created at /usr/lib/python3.7/asyncio/locks.py:272> took 0.108 seconds
```

**Environment:**
 - OS: Linux arc 4.20.6-arch1-1-ARCH #1 SMP PREEMPT Thu Jan 31 08:22:01 UTC 2019 x86_64 GNU/Linux
 - Sanic Version: 0.8.3

**Comment by chenjr0719** [comment]
Hi, I try to run your code snippet(I use a hard code path) and it worked without any error or warning. Here is my environment:
* OS: Linux 4.15.0-43-generic Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
* Python: 3.7.1
* Sanic: 0.8.3
* Video file: a 30MB mp4 file
* Client: Firefox 64.0 to open http://localhost:8000/stream

Could you describe how did you run your app and which client you used to send the request?

**Comment by syfluqs** [comment]
I was using chrome 72 as the client, maybe this is a client specific issue. I noticed that chrome makes a new request/connection every time the seek position is changed. Can't say the same for firefox.

also, i am running my app in debug mode with 1 worker process

**Comment by sjsadowski** [comment]
This appears to have been client specific. We can reopen if necessary.

**Comment by andreymal** [comment]
@sjsadowski it can be easily reproduced when the server is stopping. (Not sure if **syfluqs** stops the server, but I have the same error when my server is stopping.) I tested Chrome, Firefox, wget and nginx — every client causes this error.

You can reproduce this with a simple server:

```python
@app.route('/test')
async def test_stream(request):
    async def timer(response):
        for _ in range(50):
            await response.write(time.strftime('%H:%M:%S\n'))
            await asyncio.sleep(1)
    return stream(timer, content_type='text/plain; charset=utf-8')
```

Just send a request and press Ctrl+C:

```
[2019-03-25 00:46:03 +0300] [16927] [INFO] Goin' Fast @ http://127.0.0.1:5000
[2019-03-25 00:46:03 +0300] [16927] [INFO] Starting worker [16927]
^C[2019-03-25 00:46:06 +0300] [16927] [INFO] Stopping worker [16927]
[2019-03-25 00:46:06 +0300] [16927] [INFO] Server Stopped
Exception ignored in: <coroutine object Sanic.handle_request at 0x7f1a974e0d58>
Traceback (most recent call last):
  File "lib/python3.5/site-packages/sanic/app.py", line 974, in handle_request
    await stream_callback(response)
  File "lib/python3.5/site-packages/sanic/server.py", line 500, in stream_response
    self.keep_alive_timeout, self.keep_alive_timeout_callback
  File "uvloop/loop.pyx", line 1283, in uvloop.loop.Loop.call_later
  File "uvloop/loop.pyx", line 637, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<Sanic.handle_request() done, defined at lib/python3.5/site-packages/sanic/app.py:862> wait_for=<Future pending cb=[Task._wakeup()]>>
```
