### ISSUE TITLE
Access log writing during request timeout causes exception

### ISSUE THREAD

**Issue by ramSeraph** [huge-success/sanic#1528]
**Describe the bug**
On request timeout, the attempt from  Server write_error method to log to access log fails with the following error

```
Exception in callback <bound method WebSocketProtocol.request_timeout_callback of <sanic.websocket.WebSocketProtocol object at 0x7fe2485d1b40>> handle: <TimerHandle WebSocketProtocol.request_timeout_callback>

,stack_trace: Traceback (most recent call last):

File "uvloop/cbhandles.pyx", line 251, in uvloop.loop.TimerHandle._run
File "/venv/lib/python3.6/site-packages/sanic/websocket.py", line 31, in request_timeout_callback
  super().request_timeout_callback()
File "/venv/lib/python3.6/site-packages/sanic/server.py", line 197, in request_timeout_callback
  self.write_error(RequestTimeout("Request Timeout"))
File "/venv/lib/python3.6/site-packages/sanic/server.py", line 488, in write_error
  self.log_response(response)
File "/venv/lib/python3.6/site-packages/sanic/server.py", line 357, in log_response
  self.request.method, self.request.url
File "/venv/lib/python3.6/site-packages/sanic/request.py", line 301, in url
  (self.scheme, self.host, self.path, None, self.query_string, None)
File "/venv/lib/python3.6/site-packages/sanic/request.py", line 260, in scheme
  self.app.websocket_enabled
AttributeError: ‘NoneType’ object has no attribute ‘websocket_enabled’
```

**Code snippet**
I think this is a generic problem.. 

**Expected behavior**
A request timeout and a closing of the client connection.. 

**Environment (please complete the following information):**
 - OS: alpine 3.6
 - Version: 18.12.0 

**Additional context**
the request timeout was a very bad one, as in, the connection_made cb on the protocol was triggered but the handle_request was never triggered ( this is a guess ),  the eventloop was stuck for a different reason probably,  i am still debugging.

**Comment by yunstanford** [comment]
Yeah, it's basically because `handle_request ` has not been triggered, and it didn't reach here https://github.com/huge-success/sanic/blob/master/sanic/app.py#L884

And not sure why we need this check https://github.com/huge-success/sanic/blob/master/sanic/request.py#L378
