### ISSUE TITLE
Unable to start server -- Running run_async.py failed

### ISSUE THREAD

**Issue by lakenn** [huge-success/sanic#1551]
**Describe the bug**
[2019-04-14 19:22:02 +0800] [21512] [INFO] Goin' Fast @ http://0.0.0.0:8000
[2019-04-14 19:22:02 +0800] [21512] [ERROR] Unable to start server
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\venom\lib\site-packages\sanic\server.py", line 745, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "C:\ProgramData\Anaconda3\envs\venom\lib\asyncio\base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "C:\ProgramData\Anaconda3\envs\venom\lib\asyncio\base_events.py", line 529, in run_forever
    'Cannot run the event loop while another loop is running')
RuntimeError: Cannot run the event loop while another loop is running

**Code snippet**
Relevant source code, make sure to remove what is not necessary.

https://github.com/huge-success/sanic/blob/master/examples/run_async.py

**Expected behavior**

**Environment (please complete the following information):**
 - Version [e.g. 0.8.3]
Window and Linux, Python 3.6 or 3.7 don't work

**Additional context**

Is this example still work ?

**Comment by ahopkins** [comment]
It does... but there was a slight change. You are running `0.8.3`?

If you are in a newer release, then you would need to add `return_asyncio_server=True` to `create_server(...)`

**Comment by jrmi** [comment]
I run in this issue too. The fix proposed works. I think documentation needs update on this point.

**Comment by ahopkins** [comment]
@jrmi Agreed. I was planning on pushing a change to this when I get a chance tomorrow. Unless of course, you'd like to push a PR?

**Comment by jrmi** [comment]
Just done. Can you review it ?
