### ISSUE TITLE
Can not serve both http and websocket request on one server?

### ISSUE THREAD

**Issue by jaggerwang** [huge-success/sanic#1598]
**Describe the bug**
When serve both http and websocket request on one server, can not connect websocket. 

When connect websocket in command line using python websockets(v7.0) package.
```bash
➜  web python3 -m websockets wss://localhost:8000/ws/
Failed to connect to wss://localhost:8000/ws/: .
```

Got the following error in sanic console:
```bash
[2019-05-28 13:54:07 +0800] [50524] [ERROR] Transport closed @ ('127.0.0.1', 65350) and exception experienced during error handling
[2019-05-28 13:54:07 +0800] [50524] [DEBUG] Exception:
Traceback (most recent call last):
  File "/Users/jagger/projects/dingpan/server/venv/lib/python3.7/site-packages/sanic/server.py", line 267, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jagger/projects/dingpan/server/venv/lib/python3.7/site-packages/sanic/server.py", line 515, in write_error
    self.transport.write(response.output(version))
AttributeError: 'coroutine' object has no attribute 'output'
/Users/jagger/projects/dingpan/server/venv/lib/python3.7/site-packages/sanic/server.py:272: RuntimeWarning: coroutine 'handle_exception' was never awaited
Coroutine created at (most recent call last)
  File "/Users/jagger/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 317, in run_module
    run_module_as_main(target, alter_argv=True)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jagger/projects/dingpan/server/dingpan/app.py", line 45, in <module>
    workers=config['WORKERS'], protocol=WebSocketProtocol)
  File "/Users/jagger/projects/dingpan/server/venv/lib/python3.7/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/Users/jagger/projects/dingpan/server/venv/lib/python3.7/site-packages/sanic/server.py", line 770, in serve
    loop.run_forever()
  File "/Users/jagger/projects/dingpan/server/venv/lib/python3.7/site-packages/sanic/websocket.py", line 52, in data_received
    super().data_received(data)
  File "/Users/jagger/projects/dingpan/server/venv/lib/python3.7/site-packages/sanic/server.py", line 272, in data_received
    self.write_error(InvalidUsage(message))
  File "/Users/jagger/projects/dingpan/server/venv/lib/python3.7/site-packages/sanic/server.py", line 513, in write_error
    response = self.error_handler.response(self.request, exception)
  File "/Users/jagger/projects/dingpan/server/venv/lib/python3.7/site-packages/sanic/handlers.py", line 129, in response
    response = handler(request, exception)
  self.write_error(InvalidUsage(message))
```

**Code snippet**
```python
from sanic import Sanic
from sanic.websocket import WebSocketProtocol

from .config import config, log_config
from .models import init_db, close_db, init_cache, close_cache
from .blueprints import (handle_exception, message_v1, ws, order_v1, stock_v1,
                         user_v1, wallet_v1)

app = Sanic(config['NAME'].capitalize(), log_config=log_config)
app.config.update(config)

app.error_handler.add(Exception, handle_exception)

app.blueprint(message_v1)
app.blueprint(order_v1)
app.blueprint(stock_v1)
app.blueprint(user_v1)
app.blueprint(wallet_v1)

app.add_websocket_route(ws, '/ws')

...

if __name__ == '__main__':
    app.run(host=config['HOST'], port=config['PORT'], debug=config['DEBUG'],
            auto_reload=config['AUTO_RELOAD'], access_log=config['ACCESS_LOG'],
            workers=config['WORKERS'], protocol=WebSocketProtocol)

```

**Environment (please complete the following information):**
 - OS: masOS
 - Version: 19.3.1

**Comment by jaggerwang** [comment]
I already tried to force update websocket version to v7.0, even though Sanic require v6.0.

**Comment by ahopkins** [comment]
Are you having trouble connecting?

Here is a pretty simple example:

```python
from sanic import Sanic, response

app = Sanic("request_stream")


@app.route("/text")
def handler_text(request):
    return response.text("Hello")


@app.websocket("/ws")
async def handler_ws(request, ws):
    print("Websocket opened")
    name = "<someone>"
    while True:
        data = f"Hello {name}"
        await ws.send(data)
        name = await ws.recv()

        if not name:
            break


if __name__ == "__main__":
    app.run(port=7777, debug=True)
```

As you can see from the output, I have no problem hitting the `/text` route even after a websocket is opened.

```
[2019-05-28 09:47:12 +0300] [29726] [INFO] Goin' Fast @ http://127.0.0.1:7777
[2019-05-28 09:47:12 +0300] [29728] [INFO] Starting worker [29728]
Websocket opened
[2019-05-28 09:47:20 +0300] - (sanic.access)[INFO][127.0.0.1:58448]: GET http://localhost:7777/text  200 5
```

---

Now, it looks like you are trying to use `websockets` as a CLI (a v7 feature) in the same virtual environment as your Sanic app. If you switch to a different virtualenv that has `websockets` 7, you can use that:

```
$ python3 -m websockets ws://localhost:7777/ws
Connected to ws://localhost:7777/ws.
< Hello <someone>
> Adam
< Hello Adam
```

---

On a side note, you do not need to manually configure `protocol=WebSocketProtocol`. Sanic will automatically set it up once you add a `websocket` route. ;-)

I am closing this for now because it does not appear to be a Sanic issue. Please feel free to continue the conversation.
