### ISSUE TITLE
what can I do?

### ISSUE THREAD

**Issue by topmy** [huge-success/sanic#1686]
[2019-09-30 19:10:27 +0800] [1118] [ERROR] Exception occurred while handling uri: unknown
Traceback (most recent call last):
  File "/home/hechi/anaconda3/lib/python3.7/site-packages/sanic/server.py", line 251, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method

**Comment by Tronic** [comment]
Are you trying to use non-standard HTTP methods? In that case, see #1646 for solution.

**Comment by topmy** [comment]
Thanks!------------------ 原始邮件 ------------------
发件人: "L. K&#xE4;rkk&#xE4;inen"<notifications@github.com>
发送时间: 2019年9月30日(星期一) 晚上10:01
收件人: "huge-success/sanic"<sanic@noreply.github.com>;
抄送: "topmy"<vianus@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [huge-success/sanic] what can I do? (#1686)



Are you trying to use non-standard HTTP methods? In that case, see #1646 for solution.
 
&mdash;
