### ISSUE TITLE
High load causes Oracle database error like ORA-01013、ORA-01002、ORA-03106

### ISSUE THREAD

**Issue by vamkaxifa** [huge-success/sanic#1706]
**Describe the bug**
Use sanic as web framework, use DButils to access  oracle database, set `workers=8` (which is bigger than 1) to sanic. Under high load giving by  [sige](https://www.joedog.org/siege-home/), I got ORA errors like:
```
Traceback (most recent call last):
  File "sanicdemo.py", line 30, in health
    health_check()
  File "sanicdemo.py", line 23, in health_check
    return pool.row_sql(sql=sql, param={})
  File "/app/QuestionInvestgationProject/Database.py", line 122, in row_sql
    raise e
  File "/app/QuestionInvestgationProject/Database.py", line 113, in row_sql
    result_db = cursor.execute(sql, param)
  File "/soft/python3.7.2/lib/python3.7/site-packages/DBUtils/SteadyDB.py", line 605, in tough_method
    result = method(*args, **kwargs)  # try to execute
cx_Oracle.DatabaseError: ORA-03106: 致命的双工通信协议错误

Traceback (most recent call last):
  File "sanicdemo.py", line 30, in health
    health_check()
  File "sanicdemo.py", line 23, in health_check
    return pool.row_sql(sql=sql, param={})
  File "/app/QuestionInvestgationProject/Database.py", line 122, in row_sql
    raise e
  File "/app/QuestionInvestgationProject/Database.py", line 118, in row_sql
    result = result_db.fetchall()
cx_Oracle.DatabaseError: ORA-01002: 提取违反顺序

Traceback (most recent call last):
  File "sanicdemo.py", line 30, in health
    health_check()
  File "sanicdemo.py", line 23, in health_check
    return pool.row_sql(sql=sql, param={})
  File "/app/QuestionInvestgationProject/Database.py", line 122, in row_sql
    raise e
  File "/app/QuestionInvestgationProject/Database.py", line 118, in row_sql
    result = result_db.fetchall()
cx_Oracle.OperationalError: ORA-01013: 用户请求取消当前的操作
```

My demo is as below:
```
import traceback
import os
import cx_Oracle
from sanic import Sanic
from sanic.response import json
from DBUtils.PooledDB import PooledDB

app = Sanic(__name__)

os.environ['NLS_LANG'] = 'SIMPLIFIED CHINESE_CHINA.UTF8'

pool = PooledDB(cx_Oracle,
                threaded=True,
                user='user',
                password='pwd',
                dsn='1*.*.*.*/*',
                mincached=10,
                maxcached=50,
                maxshared=1,
                maxconnections=50)


def health_check():
    sql = '''SELECT sysdate FROM DUAL '''
    try:
        conn = pool.connection()
        cursor = conn.cursor()
        result_db = cursor.execute(sql)
        result = result_db.fetchall()
        return result
    except Exception as e:
        raise e
    finally:
        try:
            if cursor:
                cursor.close()
            if conn:
                conn.close()
        except Exception as e:
            raise e


@app.route("/healthcheck")
async def health(request):
    try:
        res = health_check()
        return json({"ok": res})
    except Exception as e:
        err = traceback.format_exc()
        print(err)
        return json({"ok": err})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=7777, debug=False, access_log=False, log_config=None, workers=8)
```

BTW, noting that , setting `workers=1` seems won't cause those errors. 

I'm wondering that is there any solution  to solve this situation.  Obviously, setting `workers=1` will lower performance which is not I want.  

Thanks for your attention.  

**Code snippet**
Relevant source code, make sure to remove what is not necessary.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Linux
 - Version: Linux e78293dfbf64 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**python**
version: python3.7.2

**sanic**
version: 6.0.1

**DBUtils**
version:1.3

**cx_Oracle**
version: 7.1.2

**Oracle database**
version: 11.2.0.3

**Comment by harshanarayana** [comment]
@vamkaxifa I don't believe this has anything to do with `sanic` as such. This behavior seems to be related to the db driver `cx_Oracle` (based on the ORA-xxxx errors). 

I haven't used that drive in a long time, so I am not entirely sure about the async support for that driver.

**Comment by sjsadowski** [comment]
The ORA- errors are returns from oracle itself, should be able to look them up in oracle's error table

**Comment by vamkaxifa** [comment]
Thanks for your attention， I have found some information on [issue](https://bitbucket.org/anthony_tuininga/cx_oracle/issues/8/gevent-eventlet-support) which says that  cx_Oracle uses OCI(Oracle Call Interface), which doesn't provide asynchronous functions. So, thank your guys!

**Comment by sjsadowski** [comment]
Sounds like this one is good for now - closing.
