### ISSUE TITLE
Using request.url_for throws KeyError: 'SERVER_NAME' in 19.9.0

### ISSUE THREAD

**Issue by roemba** [huge-success/sanic#1707]
**Describe the bug**
Running Sanic behind a proxy and trying to generate an url using `request.url_for` throws a KeyError. This used to work but now Sanic suddenly requires a SERVER_NAME in order to do this. I get the following trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 942, in handle_request
    response = await response
  File "/app/tsauth/views/activate.py", line 41, in init_activate
    request=request)
  File "/usr/local/lib/python3.7/site-packages/mako/template.py", line 476, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python3.7/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/usr/local/lib/python3.7/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python3.7/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "transaction_mako", line 60, in render_body
  File "/usr/local/lib/python3.7/site-packages/sanic/request.py", line 522, in url_for
    if "//" in self.app.config.SERVER_NAME:
  File "/usr/local/lib/python3.7/site-packages/sanic/config.py", line 54, in __getattr__
    raise AttributeError("Config has no '{}'".format(ke.args[0]))
AttributeError: Config has no 'SERVER_NAME'
[2019-10-23 12:38:09 +0000] - (sanic.access)[INFO][<redacted>:33328]: GET <redacted>  500 144
10/23/2019 12:38:09 PM ERROR Exception occurred while handling uri: '<redacted>'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sanic/config.py", line 52, in __getattr__
    return self[attr]
KeyError: 'SERVER_NAME'
```

**Code snippet**
`request.url_for("static",  name='static', filename="badge.png")`

**Expected behavior**
`request.url_for` should generate a full url with the given path, e.g. `https://hostname:port/static/badge.png`. As I am running my server behind a proxy, I do not want to hardcode the hostname in the SERVER_NAME. This used to work with Sanic version 19.6.3.

**Environment (please complete the following information):**
 - Python 3.7 Docker container, Kubernetes v1.16.2 with nginx-ingress 0.26.1
 - Sanic version 19.9.0

**Additional context**
The calling code to `request.url_for` has not changed since the Sanic version update. 
The documentation also does not speak a word about why the SERVER_NAME variable needs to be configured...

**Comment by harshanarayana** [comment]
```python
if "//" in self.app.config.SERVER_NAME:
    return self.app.url_for(view_name, _external=True, **kwargs)
```
I believe this got introduced as part of 1e4b1c4d1a907af559dcf91b697debd60d94bbd7

This can easily be mitigated with the help of a `get` method. Opening a PR for the same.

**Comment by Tronic** [comment]
@roemba As a workaround until the fix gets released, you may define `app.config.SERVER_NAME = ""`.

**Comment by roemba** [comment]
Thanks for the quick response! Will try out the workaround today.
