### ISSUE TITLE
Single Worker: RuntimeError - Event loop stopped before Future completed.

### ISSUE THREAD

**Issue by NurFaizin** [huge-success/sanic#1813]
I have an error `RuntimeError - Event loop stopped before Future completed` when I run Sanic with `workers=1` and `debug=True`.  But when I set the workers to more than 1 it shut down gracefully. When I run with multiple workers it shows that it receives **SIGINT** before shut down, but not on single worker. Note: I use `Ctrl+C `to kill the server.

Environment:
MacOS Catalina
Python 3.7.7
Sanic 19.12.2

**Comment by Tronic** [comment]
I cannot reproduce this. Are you using `app.add_task` or other background tasks in your application? Can you post code? How do you run Sanic (via `-m sanic your.app` or `app.run(...)` or some other way)?

**Comment by NurFaizin** [comment]
No, I just try with getting started code like this:

_app.py_
```python
from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.route('/')
async def hello_world(request):
    return json({"hello": "world"})

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8000, debug=True, access_log=False)
```

When it uses a single worker, I got this error:
```
app.py:4: DeprecationWarning: Sanic(name=None) is deprecated and None value support for `name` will be removed in the next release. Please use Sanic(name='your_application_name') instead.
  app = Sanic()
[2020-03-20 16:04:04 +0700] [85276] [DEBUG]

                 Sanic
         Build Fast. Run Fast.


[2020-03-20 16:04:04 +0700] [85276] [INFO] Goin' Fast @ http://0.0.0.0:8000
app.py:4: DeprecationWarning: Sanic(name=None) is deprecated and None value support for `name` will be removed in the next release. Please use Sanic(name='your_application_name') instead.
  app = Sanic()
[2020-03-20 16:04:04 +0700] [85278] [INFO] Starting worker [85278]
^C[2020-03-20 16:04:13 +0700] [85278] [INFO] Stopping worker [85278]
[2020-03-20 16:04:13 +0700] [85278] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/Users/faiz/.local/share/virtualenvs/test-MVzNdlDJ/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/Users/faiz/.local/share/virtualenvs/test-MVzNdlDJ/lib/python3.7/site-packages/sanic/server.py", line 942, in serve
    loop.run_until_complete(asyncio.sleep(0.1))
  File "uvloop/loop.pyx", line 1454, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    app.run(host="0.0.0.0", port=8000, debug=True, access_log=False)
  File "/Users/faiz/.local/share/virtualenvs/test-MVzNdlDJ/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/Users/faiz/.local/share/virtualenvs/test-MVzNdlDJ/lib/python3.7/site-packages/sanic/server.py", line 942, in serve
    loop.run_until_complete(asyncio.sleep(0.1))
  File "uvloop/loop.pyx", line 1454, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
```

But when I set the workers to more than 1, I got this:
```
app.py:4: DeprecationWarning: Sanic(name=None) is deprecated and None value support for `name` will be removed in the next release. Please use Sanic(name='your_application_name') instead.
  app = Sanic()
[2020-03-20 16:06:23 +0700] [85920] [DEBUG]

                 Sanic
         Build Fast. Run Fast.


[2020-03-20 16:06:23 +0700] [85920] [INFO] Goin' Fast @ http://0.0.0.0:8000
[2020-03-20 16:06:23 +0700] [85921] [INFO] Starting worker [85921]
[2020-03-20 16:06:23 +0700] [85922] [INFO] Starting worker [85922]
^C[2020-03-20 16:06:36 +0700] [85920] [INFO] Received signal SIGINT. Shutting down.
[2020-03-20 16:06:36 +0700] [85922] [INFO] Stopping worker [85922]
[2020-03-20 16:06:36 +0700] [85921] [INFO] Stopping worker [85921]
[2020-03-20 16:06:36 +0700] [85920] [INFO] Server Stopped
```

I see  `Received signal SIGINT. Shutting down.` when it uses more than 1 worker, and it shut down gracefully, but not on single worker.

**Comment by Tronic** [comment]
Okay, looks like something stops the loop while graceful shutdown is still in progress. Perhaps because all connections are already shut down. This seems similar to #810, which is supposed to be already fixed in #815. Any other developers willing to take a look?

**Comment by Vishnu-priyan** [comment]
`04-30 14:50:58 +0530] [7190] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/adf/envs/py37-venv/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/home/adf/envs/py37-venv/lib/python3.7/site-packages/sanic/server.py", line 942, in serve
    loop.run_until_complete(asyncio.sleep(0.1))
  File "uvloop/loop.pyx", line 1454, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
ERROR:sanic.error:Experienced exception while trying to serve
`
I'm facing this exact issue, for 1 worker.

**Comment by hongye007** [comment]
sanic 21.3.0 + ， auto_reload=True(auto_reload=False everything is ok)   then hit ctrl+c get same problem : 

Traceback (most recent call last):
  File "/opt/miniconda3/envs/P38/lib/python3.8/site-packages/sanic/mixins/runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "/opt/miniconda3/envs/P38/lib/python3.8/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/opt/miniconda3/envs/P38/lib/python3.8/site-packages/sanic/server/runners.py", line 191, in serve
    loop.run_until_complete(app._server_event("shutdown", "after"))
  File "uvloop/loop.pyx", line 1499, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
Traceback (most recent call last):
  File "app.py", line 80, in <module>
    app.run(host=_host, port=_port, debug=_debug, access_log=_log, auto_reload=True)
  File "/opt/miniconda3/envs/P38/lib/python3.8/site-packages/sanic/mixins/runner.py", line 145, in run
    self.__class__.serve(primary=self)  # type: ignore
  File "/opt/miniconda3/envs/P38/lib/python3.8/site-packages/sanic/mixins/runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "/opt/miniconda3/envs/P38/lib/python3.8/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/opt/miniconda3/envs/P38/lib/python3.8/site-packages/sanic/server/runners.py", line 191, in serve
    loop.run_until_complete(app._server_event("shutdown", "after"))
  File "uvloop/loop.pyx", line 1499, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
