### ISSUE TITLE
Is there any method to use swagger UI automatically?

### ISSUE THREAD

**Issue by sunshineinwater** [huge-success/sanic#1829]
Is there any method to use swagger UI automatically?  like Fastapi.

**Comment by Tronic** [comment]
Would this do? https://github.com/huge-success/sanic-openapi

**Comment by sunshineinwater** [comment]
> Would this do? https://github.com/huge-success/sanic-openapi

It seems doesn't work now? I open it's example code, but shows some problems.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/15187861/78424771-57eab300-76a2-11ea-8265-a97577dad711.png">

**Comment by Tronic** [comment]
Which Sanic version are you using, and what does it print in console? I just tried sanic-openapi-0.6.1 with Sanic git master and that at least seems to be working fine on my site.

**Comment by sunshineinwater** [comment]
> Which Sanic version are you using, and what does it print in console? I just tried sanic-openapi-0.6.1 with Sanic git master and that at least seems to be working fine on my site.

**Sanic version is 19.12.2**

**Error print in console is:**
```
[2020-04-04 18:58:10 +0800] [11989] [INFO] Starting worker [11989]
[2020-04-04 18:58:19 +0800] [11989] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:8000/'
Traceback (most recent call last):
  File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
[2020-04-04 18:58:19 +0800] - (sanic.access)[INFO][127.0.0.1:58182]: GET http://0.0.0.0:8000/  404 32
[2020-04-04 18:58:21 +0800] - (sanic.access)[INFO][127.0.0.1:58182]: GET http://0.0.0.0:8000/swagger/swagger-config  200 2
[2020-04-04 18:58:21 +0800] - (sanic.access)[INFO][127.0.0.1:58191]: GET http://0.0.0.0:8000/swagger/swagger-config  200 2
[2020-04-04 18:58:21 +0800] [11989] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:8000/swagger/swagger.json'
Traceback (most recent call last):
  File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic/app.py", line 974, in handle_request
    response = handler(request, *args, **kwargs)
  File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic_openapi/swagger.py", line 263, in spec
    return json(swagger_blueprint._spec)
  File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic/response.py", line 234, in json
    dumps(body, **kwargs),
TypeError: � is not JSON serializable
[2020-04-04 18:58:21 +0800] - (sanic.access)[INFO][127.0.0.1:58182]: GET http://0.0.0.0:8000/swagger/swagger.json  500 2603
[2020-04-04 18:58:21 +0800] [11989] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:8000/swagger/swagger.json'
Traceback (most recent call last):
  File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic/app.py", line 974, in handle_request
    response = handler(request, *args, **kwargs)
  File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic_openapi/swagger.py", line 263, in spec
    return json(swagger_blueprint._spec)
  File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic/response.py", line 234, in json
    dumps(body, **kwargs),
TypeError: � is not JSON serializable
[2020-04-04 18:58:21 +0800] - (sanic.access)[INFO][127.0.0.1:58182]: GET http://0.0.0.0:8000/swagger/swagger.json  500 2603
[2020-04-04 18:58:26 +0800] [11989] [DEBUG] KeepAlive Timeout. Closing connection.
[2020-04-04 18:58:26 +0800] [11989] [DEBUG] KeepAlive Timeout. Closing connection.
```

**Comment by Tronic** [comment]
```
  File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic/response.py", line 234, in json
    dumps(body, **kwargs),
TypeError: � is not JSON serializable
```

Looks like a compatibility problem with Chinese characters, although I cannot see exactly where that error message would be produced. Is it possible that you use old 8-bit encodings or anything other than valid UTF-8 somewhere?

In any case, sanic-swagger has already produced a dict with the definition of your site, but converting that to JSON fails for some reason. You could try installing the ujson package (the error message looks like it comes from Python's built-in json, suggesting that you didn't install Sanic with ujson enabled).

**Comment by sunshineinwater** [comment]
> ```
>   File "/Users/zhangxuewei/Documents/GitHub/myPython/公共venv/lib/python3.7/site-packages/sanic/response.py", line 234, in json
>     dumps(body, **kwargs),
> TypeError: � is not JSON serializable
> ```
> 
> 
> Looks like a compatibility problem with Chinese characters, although I cannot see exactly where that error message would be produced. Is it possible that you use old 8-bit encodings or anything other than valid UTF-8 somewhere?
> 
> 
> In any case, sanic-swagger has already produced a dict with the definition of your site, but converting that to JSON fails for some reason. You could try installing the ujson package (the error message looks like it comes from Python's built-in json, suggesting that you didn't install Sanic with ujson enabled).

Here is the new error print without Chinese characters and reinstall ujson.

```
[2020-04-04 20:08:05 +0800] [12516] [INFO] Goin' Fast @ http://0.0.0.0:8000
/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/main.py:9: DeprecationWarning: Sanic(name=None) is deprecated and None value support for `name` will be removed in the next release. Please use Sanic(name='your_application_name') instead.
  app = Sanic()
[2020-04-04 20:08:05 +0800] [12518] [INFO] Starting worker [12518]
[2020-04-04 20:08:09 +0800] [12518] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:8000/'
Traceback (most recent call last):
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
[2020-04-04 20:08:09 +0800] - (sanic.access)[INFO][127.0.0.1:61716]: GET http://0.0.0.0:8000/  404 32
[2020-04-04 20:08:12 +0800] [12518] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:8000/'
Traceback (most recent call last):
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/app.py", line 940, in handle_request
    handler, args, kwargs, uri, name = self.router.get(request)
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/router.py", line 411, in get
    return self._get(request.path, request.method, "")
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/router.py", line 475, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
[2020-04-04 20:08:12 +0800] - (sanic.access)[INFO][127.0.0.1:61717]: GET http://0.0.0.0:8000/  404 32
[2020-04-04 20:08:13 +0800] - (sanic.access)[INFO][127.0.0.1:61717]: GET http://0.0.0.0:8000/swagger/swagger-config  200 2
[2020-04-04 20:08:13 +0800] - (sanic.access)[INFO][127.0.0.1:61718]: GET http://0.0.0.0:8000/swagger/swagger-config  200 2
[2020-04-04 20:08:13 +0800] [12518] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:8000/swagger/swagger.json'
Traceback (most recent call last):
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/app.py", line 974, in handle_request
    response = handler(request, *args, **kwargs)
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic_openapi/swagger.py", line 263, in spec
    return json(swagger_blueprint._spec)
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/response.py", line 234, in json
    dumps(body, **kwargs),
TypeError: <sanic_openapi.spec.Spec object at 0x10408d0d0> is not JSON serializable
[2020-04-04 20:08:13 +0800] - (sanic.access)[INFO][127.0.0.1:61717]: GET http://0.0.0.0:8000/swagger/swagger.json  500 2730
[2020-04-04 20:08:13 +0800] [12518] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:8000/swagger/swagger.json'
Traceback (most recent call last):
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/app.py", line 974, in handle_request
    response = handler(request, *args, **kwargs)
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic_openapi/swagger.py", line 263, in spec
    return json(swagger_blueprint._spec)
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/response.py", line 234, in json
    dumps(body, **kwargs),
TypeError: <sanic_openapi.spec.Spec object at 0x10408d0d0> is not JSON serializable
[2020-04-04 20:08:13 +0800] - (sanic.access)[INFO][127.0.0.1:61717]: GET http://0.0.0.0:8000/swagger/swagger.json  500 2730
[2020-04-04 20:08:14 +0800] - (sanic.access)[INFO][127.0.0.1:61716]: GET http://0.0.0.0:8000/swagger/swagger-config  200 2
[2020-04-04 20:08:14 +0800] - (sanic.access)[INFO][127.0.0.1:61727]: GET http://0.0.0.0:8000/swagger/swagger-config  200 2
[2020-04-04 20:08:14 +0800] [12518] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:8000/swagger/swagger.json'
Traceback (most recent call last):
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/app.py", line 974, in handle_request
    response = handler(request, *args, **kwargs)
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic_openapi/swagger.py", line 263, in spec
    return json(swagger_blueprint._spec)
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/response.py", line 234, in json
    dumps(body, **kwargs),
TypeError: <sanic_openapi.spec.Spec object at 0x10408d0d0> is not JSON serializable
[2020-04-04 20:08:14 +0800] - (sanic.access)[INFO][127.0.0.1:61716]: GET http://0.0.0.0:8000/swagger/swagger.json  500 2730
[2020-04-04 20:08:14 +0800] [12518] [ERROR] Exception occurred while handling uri: 'http://0.0.0.0:8000/swagger/swagger.json'
Traceback (most recent call last):
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/app.py", line 974, in handle_request
    response = handler(request, *args, **kwargs)
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic_openapi/swagger.py", line 263, in spec
    return json(swagger_blueprint._spec)
  File "/Users/zhangxuewei/Documents/GitHub/sanic-openapi/examples/cars/venv/lib/python3.7/site-packages/sanic/response.py", line 234, in json
    dumps(body, **kwargs),
TypeError: <sanic_openapi.spec.Spec object at 0x10408d0d0> is not JSON serializable
[2020-04-04 20:08:14 +0800] - (sanic.access)[INFO][127.0.0.1:61716]: GET http://0.0.0.0:8000/swagger/swagger.json  500 2730
[2020-04-04 20:08:18 +0800] [12518] [DEBUG] KeepAlive Timeout. Closing connection.
[2020-04-04 20:08:18 +0800] [12518] [DEBUG] KeepAlive Timeout. Closing connection.
```

**Comment by Tronic** [comment]
Looks like this was fixed after the latest release in https://github.com/huge-success/sanic-openapi/pull/157

You can try with the development version by
```
pip install git+https://github.com/huge-success/sanic-openapi.git
```

**Comment by sunshineinwater** [comment]
> Looks like this was fixed after the latest release in [huge-success/sanic-openapi#157](https://github.com/huge-success/sanic-openapi/pull/157)
> 
> You can try with the development version by
> 
> ```
> pip install git+https://github.com/huge-success/sanic-openapi.git
> ```

It works! thx a lot !!

**Comment by ashleysommer** [comment]
Can this be closed now?
