### ISSUE TITLE
[ERROR] Please Help Me

### ISSUE THREAD

**Issue by GuckTubeYT** [huge-success/sanic#1840]
how to Quite or fix this error
``
[2020-05-01 10:09:54 +0700] [8892] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1/t1'
Traceback (most recent call last):
  File "C:\Users\rahmat\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sanic\app.py", line 945, in handle_request
    response = await self._run_request_middleware(
  File "C:\Users\rahmat\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sanic\app.py", line 1297, in _run_request_middleware
    response = middleware(request)
  File "C:\Users\rahmat\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sanic_limiter\extension.py", line 239, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "C:\Users\rahmat\AppData\Local\Programs\Python\Python38-32\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\rahmat\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sanic_limiter\extension.py", line 236, in __check_request_limit
    raise RateLimitExceeded(exc_description)
sanic_limiter.errors.RateLimitExceeded: 10 per 1 minute
``

**Comment by ahopkins** [comment]
This looks like an exception from a plugin you have installed (`sanic_limiter`). It is saying that you had more than 10 requests in one minute, which seems like a very low threshhold. Looks like it is operating properly. 

Nonetheless, you should ask in [their GitHub page](https://github.com/bohea/sanic-limiter/issues) or the [Sanic community forums](https://community.sanicframework.org/).
