### ISSUE TITLE
Windows Logging Python 3.8

### ISSUE THREAD

**Issue by ahopkins** [huge-success/sanic#1938]
I have recently noticed [this error in appveryor builds](https://ci.appveyor.com/project/sjsadowski/sanic/builds/35454061/job/kiieujoex767uwna). Seems to be limited to Py38.

It is [this test in `tests/test_logging.py`](https://github.com/huge-success/sanic/blob/master/tests/test_logging.py#L129)

Can someone with a Windows machine take a look at this?

```
_________________________________ test_logger _________________________________
caplog = <_pytest.logging.LogCaptureFixture object at 0x000000E28E0AE550>
    def test_logger(caplog):
        rand_string = str(uuid.uuid4())
    
        app = Sanic(name=__name__)
    
        @app.get("/")
        def log_info(request):
            logger.info(rand_string)
            return text("hello")
    
        with caplog.at_level(logging.INFO):
            request, response = app.test_client.get("/")
    
        port = request.server_port
    
        # Note: testing with random port doesn't show the banner because it doesn't
        # define host and port. This test supports both modes.
        if caplog.record_tuples[0] == (
            "sanic.root",
            logging.INFO,
            f"Goin' Fast @ http://127.0.0.1:{port}",
        ):
            caplog.record_tuples.pop(0)
    
>       assert caplog.record_tuples[0] == (
            "sanic.root",
            logging.INFO,
            f"http://127.0.0.1:{port}/",
        )
E       AssertionError: assert ('asyncio', 4... cancelled>>') == ('sanic.root'....0.0.1:2040/')
E         At index 0 diff: 'asyncio' != 'sanic.root'
E         Use -v to get the full diff
tests\test_logging.py:153: AssertionError
----------------------------- Captured log setup ------------------------------
DEBUG    asyncio:proactor_events.py:623 Using proactor: IocpProactor
---------------------------- Captured stdout call -----------------------------
[2020-09-28 22:46:46 -0000] - (sanic.root)[INFO]: http://127.0.0.1:2040/
[2020-09-28 22:46:46 -0000] - (sanic.root)[INFO]: 8c241bab-6591-4f09-87f8-c439ed3da740
[2020-09-28 22:46:46 -0000] - (sanic.access)[INFO]: 
[2020-09-28 22:46:46 -0000] - (sanic.root)[INFO]: Starting worker [2352]
[2020-09-28 22:46:46 -0000] - (sanic.root)[INFO]: Stopping worker [2352]
[2020-09-28 22:46:46 -0000] - (sanic.root)[INFO]: Server Stopped
---------------------------- Captured stderr call -----------------------------
INFO:     ASGI 'lifespan' protocol appears unsupported.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000000E28A393E50>
Traceback (most recent call last):
  File "c:\python38-x64\Lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "c:\python38-x64\Lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "c:\python38-x64\Lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "c:\python38-x64\Lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000000E28A393E50>
Traceback (most recent call last):
  File "c:\python38-x64\Lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "c:\python38-x64\Lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "c:\python38-x64\Lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "c:\python38-x64\Lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
------------------------------ Captured log call ------------------------------
ERROR    asyncio:base_events.py:1692 Task was destroyed but it is pending!
```

**Comment by ahopkins** [comment]
Well.... now they are passing and nothing changed. Go figure.
https://ci.appveyor.com/project/ahopkins/sanic/build/job/6fxjxvtql76l4xpa
