### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'request_class'

### ISSUE THREAD

**Issue by jiaxiaolei** [huge-success/sanic#909]
I encounter the `custom_protocol` demo in `sanic.readthedocs.io/en/latest`. I found, some times, 
the `server` return `TypeError` after some minutes of starting it.

Does anyone others face the same question with me? 

Any replay will be appreciate.

python version: py3.6.1
sanic version: '0.6.0'
```
(py3.6.1env) [root@uop-test-ad4b7b17-44b1-4657-ab30-8593ece79d7b my_sanic_project]# ipython
Python 3.6.1 (default, Jul 15 2017, 13:58:07)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sanic

In [2]: sanic.__version__
Out[2]: '0.6.0'
```

```
# url: http://sanic.readthedocs.io/en/latest/sanic/custom_protocol.html
# filename:  httpprotocol_sanic.py

from sanic import Sanic
from sanic.server import HttpProtocol
from sanic.response import text

app = Sanic(__name__)


class CustomHttpProtocol(HttpProtocol):

    def __init__(self, *, loop, request_handler, error_handler,
                 signal, connections, request_timeout, request_max_size):
        super().__init__(
            loop=loop, request_handler=request_handler,
            error_handler=error_handler, signal=signal,
            connections=connections, request_timeout=request_timeout,
            request_max_size=request_max_size)

    def write_response(self, response):
        if isinstance(response, str):
            response = text(response)
        self.transport.write(
            response.output(self.request.version)
        )
        self.transport.close()


@app.route('/')
async def string(request):
    return 'string'


@app.route('/1')
async def response(request):
    return text('response')

app.run(host='0.0.0.0', port=8000, protocol=CustomHttpProtocol)
```

```
$ python httpprotocol_sanic.py
2017-08-22 19:34:47 - (sanic)[INFO]: Goin' Fast @ http://0.0.0.0:8000
2017-08-22 19:34:47 - (sanic)[INFO]: Starting worker [6562]


Unhandled exception in event loop
Traceback (most recent call last):
  File "uvloop/handles/streamserver.pyx", line 126, in uvloop.loop.__uv_streamserver_on_listen (uvloop/loop.c:78941)
  File "uvloop/handles/streamserver.pyx", line 49, in uvloop.loop.UVStreamServer._on_listen (uvloop/loop.c:77750)
TypeError: __init__() got an unexpected keyword argument 'request_class'
```

**Comment by LynnShaw** [comment]
I have meet the same question, and solve it by delete `__init__` function, but I still have no idea about how did the problem occur?
