### ISSUE TITLE
How to safely close the aioredis connection when using Sanic?

### ISSUE THREAD

**Issue by vg-pulsepoint** [huge-success/sanic#989]
I wrote a script that uses Sanic with aioredis,which keeps throws errors when I shutdown Sanic. The errors disappear when I remove the "after_server_stop" block below, but I would prefer to leave it in and close the connection properly. Please advise, both my code and error message are below and I'm running aioredis v0.3.3 and Sanic v0.6

	import os, datetime, logging
	from sanic import Sanic
	from sanic import response
	import asyncio
	import uvloop
	import aiohttp
	import aioredis
	from sanic.config import Config

	redis_host = os.environ.get('redis_host', "localhost")
	redis_port = int(os.environ.get('redis_port', 6379))

	Config.REQUEST_TIMEOUT = 120

	asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

	app = Sanic(__name__)

	@app.listener('before_server_start')
	async def before_server_start(app, loop):
		app.redis_pool = await aioredis.create_connection( (redis_host, redis_port), loop=loop )

	@app.listener('after_server_stop')
	async def after_server_stop(app, loop):
		app.redis_pool.close()
		await app.redis_pool.wait_closed()

	@app.route('/fetch', methods=['POST'])
	async def handle_request(request):
		print(request.body)
		data = await app.redis_pool.execute('lrange', 'text', 0, -1)
		return response.json({"data": data})

	loop = asyncio.get_event_loop()

	app.run(host="0.0.0.0", port=5000, workers=4, debug=True)

This is the error message:

	Process Process-4:
	Traceback (most recent call last):
	  File "/Users/username/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
	    self.run()
	  File "/Users/username/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
	    self._target(*self._args, **self._kwargs)
	  File "/Users/username/anaconda3/lib/python3.6/site-packages/sanic/server.py", line 564, in serve
	    trigger_events(after_stop, loop)
	  File "/Users/username/anaconda3/lib/python3.6/site-packages/sanic/server.py", line 419, in trigger_events
	    loop.run_until_complete(result)
	  File "uvloop/loop.pyx", line 1201, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25601)
	RuntimeError: Event loop stopped before Future completed.
	2017-10-19 15:28:07 - (sanic)[INFO]: Server Stopped

**Comment by yunstanford** [comment]
I tested your code with  `aioredis 0.3.4` and `sanic 0.6.0`, works fine in my local dev box without any issue.

```
[2017-10-29 17:06:07 -0700] [1041] [INFO] Goin' Fast @ http://0.0.0.0:5000
[2017-10-29 17:06:07 -0700] [1042] [INFO] Starting worker [1042]
[2017-10-29 17:06:07 -0700] [1043] [INFO] Starting worker [1043]
[2017-10-29 17:06:07 -0700] [1044] [INFO] Starting worker [1044]
[2017-10-29 17:06:07 -0700] [1045] [INFO] Starting worker [1045]
b''
[2017-10-29 17:06:11 -0700] - (sanic.access)[INFO][127.0.0.1:62038]: GET http://0.0.0.0:5000/fetch  200 11
^C[2017-10-29 17:06:16 -0700] [1043] [INFO] Stopping worker [1043]
[2017-10-29 17:06:16 -0700] [1042] [INFO] Stopping worker [1042]
[2017-10-29 17:06:16 -0700] [1044] [INFO] Stopping worker [1044]
[2017-10-29 17:06:16 -0700] [1045] [INFO] Stopping worker [1045]
[2017-10-29 17:06:16 -0700] [1041] [INFO] Received signal SIGINT. Shutting down.
[2017-10-29 17:06:16 -0700] [1041] [INFO] Server Stopped
```

**Comment by r0fls** [comment]
Hi @vg-pulsepoint, I'm going to close this soon unless you can provide us with an update.
